data = [
    {
        "_id": "00001001-501",
        "title": "Ground Cafe de Olla",
        "description": " Ground coffee; De Olla: This coffee is roasted with cinnamon infusion",
        "price": 12.50,
        "stock": 20,
        "category": "Ground",
        "discount": 0,
    },
    {
        "_id": "00001002-501",
        "title": "Ground Cafe with Chocolate",
        "description": " Ground coffee; Mexican Cocoa Flavor: This coffee is roasted with Rich Mexican Chocolate",
        "price": 12.50,
        "stock": 11,
        "category": "Ground",
        "discount": 0,
    },
    {
        "_id": "00001003-501",
        "title": "Ground Coca Cafe: Light Roast",
        "description": " Ground coffee; Light Roast: This coffee is Light/Blonde roasted",
        "price": 12.50,
        "stock": 21,
        "category": "Ground",
        "discount": 0,
    },
    {
        "_id": "00001004-501",
        "title": "Ground Coca Cafe: Medium Roast",
        "description": " Ground coffee; Medium Roast: This coffee is Medium roasted",
        "price": 12.50,
        "stock": 8,
        "category": "Ground",
        "discount": 0,
    },
    {
        "_id": "00001005-501",
        "title": "Ground Coca Cafe: Dark Roast",
        "description": " Ground coffee; Dark Roast: This coffee is Dark roasted",
        "price": 12.50,
        "category": "Ground",
        "discount": 0,
    },
    {
        "_id": "00001006-501",
        "title": "Whole Coca Cafe: Dark Roast",
        "description": " Whole coffee beans; De Olla: This coffee is roasted with cinnamon infusion",
        "price": 10.50,
        "category": "Whole",
        "discount": 5,
    },
    {
        "_id": "00001007-501",
        "title": "Whole Cafe with Chocolate",
        "description": " Whole coffee beans; Mexican Chocolate: This coffee is roasted with cinnamon infusion",
        "price": 10.50,
        "stock": 6,
        "category": "Whole",
        "discount": 5,
    },
    {
        "_id": "00001008-501",
        "title": "Whole Coca Cafe: Light Roast",
        "description": " Whole coffee beans; Light/Blonde Roast",
        "price": 12.50,
        "stock": 13,
        "category": "Whole",
        "discount": 5,
    },
    {
        "_id": "00001009-501",
        "title": "Whole Coca Cafe: Medium Roast",
        "description": " Whole coffee beans; Medium Roast",
        "price": 10.50,
        "stock": 1,
        "category": "Whole",
        "discount": 5,
    },
    {
        "_id": "00001010-501",
        "title": "Whole Coca Cafe: Dark Roast",
        "description": " Whole coffee beans; Dark Roast",
        "price": 10.50,
        "stock": 9,
        "category": "Whole",
        "discount": 5,
    },
]