#!/bin/bash
# sudo chmod u+x runserver <- use this to assign exec permissions
# brew services start mongodb-community@5.0
# brew services stop mongodb-community@5.0
export FLASK_APP=server.py
export FLASK_ENV=development
flask run